# Generated by Django 5.2.3 on 2025-06-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_cycletime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
