# Generated by Django 5.2.3 on 2025-06-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_contract_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
